### PR TITLE
fix: Implemented output truncation and suppression on Github comments

### LINKED ISSUE #150: TF Plan output to comment on a PR fails   | body is too long (maximum is 65536 characters)
### Description

I am receiving validation error as below when plan has more than 65536 chars.
This occurs when the action tries to add new/update comment after a successful plan on the PR.
```
Error: Validation Failed: {"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

It seems that this 65536 chars is a hard limit https://github.com/orgs/community/discussions/41331 on the Github api.

To mitigate this issue, we should look at trimming the output before trying to add comment or split comments on the PR. Any other suggestion are welcome.

### GitHub Action Version

v3.0.3

### Configuration

terraformVersion: 1.5.7
cdktfVersion: 0.18.0
stackName: my-tf-stack
mode: plan-only
terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
githubToken: ${{ secrets.GITHUB_TOKEN }}

### Gist

_No response_

### Possible Solutions

Trim `messageWithTag` to first 65536 characters before executing 
`octokit.rest.issues.createComment` or `octokit.rest.issues.updateComment`

### Workarounds

Immediate resolution would be to set  `commentOnPr` and `updateComment` parameters to `false` temporarily.

### Anything Else?

_No response_

### References

_No response_

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by billyjbryant**
### Related issue

Fixes #150

### Description

I implemented two new features into the action.

1. Output is truncated to `65000` characters to ensure that the resulting Github comment does not exceed the maximum of `65536` characters.
    * The truncation occurs at the beginning of the output and truncated content is replaced with a simple disclaimer indicating truncation.
1. Implemented a new `Boolean` input called `suppressOutput` which simply serves to suppress the `cdktf` output in the comment if `commentOnPr` and `suppressOutput` are both `true`. 

### Checklist

- [x] I have updated the PR title to match [CDKTF's style guide](https://github.com/hashicorp/terraform-cdk-action/blob/main/.github/CONTRIBUTING.md#pull-requests-1)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works if applicable
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by billyjbryant** [comment]
@team-tf-cdk can I get a review on this PR?

**Comment by DanielMSchmidt** [comment]
Sorry for the late review. I think we would need to add the new option to https://github.com/hashicorp/terraform-cdk-action/blob/main/.projenrc.ts#L24 since the action.yml i projen managed.

**Comment by DanielMSchmidt** [comment]
Other than that the PR looks good to me and could be merged 👍

**Comment by billyjbryant** [comment]
@DanielMSchmidt I have updated `.projenrc.ts` accordingly.

**Comment by DanielMSchmidt** [comment]
It seems like the build is failing, it seems to indicate the checked in build is not in line with the code, could you re-run the build and check it in?

**Comment by billyjbryant** [comment]
@DanielMSchmidt I re-ran the build and committed the results.

**Comment by billyjbryant** [comment]
@DanielMSchmidt hopefully that worked. There are a lot of file changes that I didn't do (They happened after yarn build)

**Pull request closed without merging**
