### PR TITLE
feat: add parallelism flag

### LINKED ISSUE #34: Support for setting the 'parallelism' flag
Hi,

Please make the `parallelism` [feature from cdktf](https://developer.hashicorp.com/terraform/cdktf/cli-reference/commands#deploy) configurable via the Action.

Thanks in advance!
Johan

### PR DESCRIPTION
**Pull request by Maed223**
### Related issue

Fixes #34

### Description

Adds parallelism option to inputs.

### CODE REVIEW

**Review by DanielMSchmidt — COMMENTED** [review]
I don't think this makes sense. The action is currently limited to a single stack being run as far as I know. This means any setting of stack-level parallelism makes no sense if we talk about one stack being run

**Comment by ansgarm** [comment]
> I don't think this makes sense. The action is currently limited to a single stack being run as far as I know. This means any setting of stack-level parallelism makes no sense if we talk about one stack being run

@DanielMSchmidt Can't you pass `*` as the stack name? Should work for apply, shouldn't it?

**Comment by DanielMSchmidt** [comment]
Yeah it would work, but it's not the intended usage from my point of view. I would expect questions / issues about planning multiple stacks at once to come as a result which is something that we don't support out of the complexity of doing accurate plans across multiple dependent workspaces.

**Comment by ansgarm** [comment]
Makes sense, yeah 👍

**Comment by Maed223** [comment]
Changes out of scope for project

**Pull request closed without merging**
